No return from setter
yangby-cryptape/rust-property pull request #6
Opened 2020-05-28 12:52 UTC by Dushistov

For some cases it is very inconvenient to have return value in setter,
for example:

```rust
fn f() {}
fn g() -> i32 {
    17
}

fn main() {
    let x = 1;
    match x {
        1 => f(),
        2 => g(),
        3 => println!("Hi"),
        _ => println!("ohter"),
    }
}
```

this code doesn't compile, because of `g` return value,
I don't use value from setters, so it would be convenient to have such option
to make it possible for easy way to deal with generated code.

2020-06-18 06:13 UTC, yangby-cryptape commented
I will merge this PR after this discussion: [maybe the `skip` feature is redundant](https://github.com/yangby-cryptape/rust-property/pull/5#issuecomment-645800142).

2020-06-18 06:31 UTC, chaoticlonghair requested changes

2020-06-18 06:31 UTC, yangby-cryptape commented on src/parse.rs
>  const SET_TYPE_OPTIONS: (&str, Option<&[&str]>) = ("type", Some(&["ref", "own"]));
I think maybe you can just add an option here:

```suggestion
const SET_TYPE_OPTIONS: (&str, Option<&[&str]>) = ("type", Some(&["ref", "own", "none"]));
```
(Maybe the name `type` is not proper, I will rename it in future as a break change)

And add codes in the follow parts:
- Add a `None_` item:
  https://github.com/yangby-cryptape/rust-property/blob/10439969773b5ce09184455060a5522e5fc3c89e/src/parse.rs#L43-L46
- Deserialize `none` to `SetTypeConf::None_`:
  https://github.com/yangby-cryptape/rust-property/blob/10439969773b5ce09184455060a5522e5fc3c89e/src/parse.rs#L190-L195
- Generate codes:
  https://github.com/yangby-cryptape/rust-property/blob/10439969773b5ce09184455060a5522e5fc3c89e/src/lib.rs#L159-L198

2020-06-19 04:12 UTC, yangby-cryptape commented on src/lib.rs
> +                    ) -> #ret_ty {
`#[property(set(noret, type="own"))]` is pointless.
Input is a owned self but no return.

2020-06-19 09:07 UTC, Dushistov commented
`#[property(set(noret))]` is little shorter then `#[property(set(type = "none"))]`,
but I usually use it on the top of struct so it is doesn't really matter for me.
Close in favor of #8

2020-06-19 09:07 UTC, closed without merging